project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  cookie-consent: true
  twitter-card:
    creator: "@jyotirmoy21"
    site: "@rstudio"
  page-navigation: true
  page-footer: 
    left: "Copyright© 2022, Jyotirmoy Das"
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
    center: "Created with Quarto"
  title: "jyotirmoydas"
  
  navbar:
    left:
      - text: "Home"
        file: about.qmd
      - text: "Projects"
        file: maclrn.qmd
  
  sidebar:
    - title: "Home"
      style: "docked"
      contents:
        - about.qmd
        - education.qmd
        - experience.qmd
        - teaching.qmd
        - publication.qmd
        - accomplishments.qmd
    - title: "Projects"
      style: "docked"
      contents: 
        - maclrn.qmd
        - curr-proj.qmd
        - com-projects.qmd
        - postdoc1.qmd
        - phd-proj.qmd
      tools:
        - icon: twitter
          href: https://twitter.com
        - icon: github
          menu:
            - text: Source Code
              url: https://code.com
            - text: Report a Bug
              url: https://bugs.com


format:
  html:
    theme: 
      light: sketchy
      dark: [darkly, skethcy]
    css: custom.css
    toc: true



