project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  cookie-consent: true
  twitter-card:
    creator: "@jyotirmoy21"
    site: "@rstudio"
  page-navigation: true
  page-footer: 
    left: "Copyright© 2022, Jyotirmoy Das"
    right:
      - icon: slack
        href: https://app.slack.com/client/TUAD6JECU/CUAT3FRKP
      - icon: box-fill
        text: DockerHub
        href: https://hub.docker.com/u/jd21
      - icon: box-fill
        text: Google Scholar
        href: https://scholar.google.co.in/citations?user=IMBYOv8AAAAJ&hl=en
      - icon: box-fill
        text: ResearchGate
        href: https://www.researchgate.net/profile/Jyotirmoy-Das-3
      - icon: linkedin
        href: https://www.linkedin.com/in/dasjyotirmoy/
      - icon: box-fill
        text: ORCiD
        href: https://orcid.org/0000-0002-5649-4658
      - icon: box-fill
        text: Scopus
        href: https://www.scopus.com/authid/detail.uri?authorId=55764683900
      - icon: box-fill
        text: Loop
        href: https://loop.frontiersin.org/people/1519976/overview
    center: "Created with Quarto"
  title: "jyotirmoydas"
  
  navbar:
    left:
      - text: "Home"
        file: about.qmd
      - text: "Projects"
        file: maclrn.qmd
  
  sidebar:
    - title: "Home"
      style: "docked"
      contents:
        - about.qmd
        - education.qmd
        - experience.qmd
        - teaching.qmd
        - publication.qmd
        - accomplishments.qmd
    - title: "Projects"
      style: "docked"
      contents: 
        - maclrn.qmd
        - curr-proj.qmd
        - com-projects.qmd
        - postdoc1.qmd
        - phd-proj.qmd
        - mas-proj.qmd
        - bach-proj.qmd
      tools:
        - icon: twitter
          href: https://twitter.com
        - icon: github
          menu:
            - text: Source Code
              url: https://code.com
            - text: Report a Bug
              url: https://bugs.com


format:
  html:
    theme: 
      light: sketchy
      dark: [darkly, skethcy]
    css: custom.css
    toc: true



